<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQjUbQPJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQjUbQPJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQjUbQPJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQjUbQPJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQjUbQPJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'QjUbQPJ',
    'container.build_id' => '23747141',
    'container.build_time' => 1727452696,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQjUbQPJ');
